name: pelusas
description: "Aplicacion de gaticos."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.8.0+1
  url_launcher: ^6.2.4
  flutter_native_splash: ^2.4.5
  build_runner: ^2.10.5


dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon2.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#131212"
  image: "assets/app_icon2.png"
  branding: "assets/branding.png"
  branding_mode: bottom
  android_12:
    image: "assets/app_icon2.png"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#131212"
    branding: "assets/branding.png"



flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/